Ft6 class hierarchy proxy loss
feedzai/fairgbm pull request #34
Opened 2022-08-26 11:38 UTC by GoncaloArs

2022-08-30 13:50 UTC, AndreFCruz reviewed
Looks good overall :slightly_smiling_face: 

Minor comments were added

I still want to test it more thoroughly this week while you're in PTO.

2022-08-30 13:50 UTC, AndreFCruz commented on src/objective/objective_function.cpp
> +    return new ConstrainedRecallObjective(strs); //should never be called. only here for consistency with other objective functions
why was this comment added?

2022-08-30 13:50 UTC, AndreFCruz commented on src/objective/objective_function.cpp
> +    return new ConstrainedRecallObjective(strs); //should never be called. only here for consistency with other objective functions
I'd say that the FairGBM package itself is separate from its Python API and the Pulse environment. We can't use recall goal on any of those but we can still use it on the C++ module with command line interface or by loading configs from a file.

2022-08-31 14:56 UTC, sgpjesus commented
Good news :) @AlbertoEAF @AndreFCruz @GoncaloArs 

I made a local test with this PR and got the results on the processing times: 
![image](https://user-images.githubusercontent.com/36162088/187709925-2d5a1668-bc0d-44f1-a3d7-0d957a80803b.png)

We get a great increase in performance (44min cpu time to 11min). In terms of metrics, the results are the same. Just to make sure, I will compare each prediction.

2022-08-31 15:43 UTC, AndreFCruz commented on src/objective/objective_function.cpp
> +#include "proxy-loss-types/constrained_recall_objective_quadratic.hpp"
Subclasses should encapsulate proxy losses for the constraints, these classes seem to encapsulate the whole recall-objective + some-specific-proxy behavior.

2022-08-31 15:44 UTC, AndreFCruz commented on src/objective/objective_function.cpp
> +      return new ConstrainedRecallObjectiveQuadratic(config);
the hierarchy is not supposed to be under the ObjectiveClass; it's a new hierarchy of proxy losses, and those new classes from the hierarchy will be used in both constrained xentropy and constrained recall objectives.

2022-08-31 15:45 UTC, AndreFCruz requested changes
There was a bit of a misunderstanding on the class hierarchy structure.

I don't think this current implementation is even called as the standard is using `constrained_cross_entropy` :sweat_smile:

2022-09-06 10:12 UTC, AndreFCruz commented
Closed in favor of #35

2022-09-06 10:12 UTC, closed without merging

2022-09-12 13:15 UTC, AndreFCruz commented
![FPR-proxy-metrics](https://user-images.githubusercontent.com/13498941/189664020-70ebbae4-6b93-4f38-af7d-f870381a8a22.png)